# Generated by Django 3.0.4 on 2020-03-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Snp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsid', models.CharField(max_length=15)),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetics.Chromosome')),
                ('genotype', models.ManyToManyField(to='genetics.Genotype')),
            ],
        ),
        migrations.CreateModel(
            name='UserGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opensnpid', models.PositiveIntegerField(blank=True)),
                ('snp', models.ManyToManyField(through='genetics.Allele', to='genetics.Snp')),
            ],
        ),
        migrations.AddField(
            model_name='allele',
            name='genotype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genetics.Genotype'),
        ),
        migrations.AddField(
            model_name='allele',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetics.Snp'),
        ),
        migrations.AddField(
            model_name='allele',
            name='usergenome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetics.UserGenome'),
        ),
    ]
