# Generated by Django 3.0.4 on 2020-03-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snp',
            name='genotype',
        ),
        migrations.AlterField(
            model_name='snp',
            name='chromosome',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='genetics.Chromosome'),
        ),
        migrations.AlterField(
            model_name='usergenome',
            name='snp',
            field=models.ManyToManyField(blank=True, through='genetics.Allele', to='genetics.Snp'),
        ),
    ]
