# Generated by Django 3.0.4 on 2020-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0002_auto_20200314_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenome',
            name='genomefile',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
