# Generated by Django 3.0.4 on 2020-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0003_usergenome_genomefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenome',
            name='genomefile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='usergenome',
            name='opensnpid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
