# Generated by Django 3.0.4 on 2020-03-11 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeneVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True)),
                ('height', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(500)])),
                ('genome', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genetics.UserGenome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
