# Generated by Django 3.0.4 on 2020-03-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_creator_genevisitor'),
        ('trait', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genevisitor',
            name='onensptrait',
            field=models.ManyToManyField(to='trait.OneSNPTrait'),
        ),
        migrations.AddField(
            model_name='genevisitor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
