# Generated by Django 3.0.4 on 2020-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200314_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='genevisitor',
            name='genomefile',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
