# Generated by Django 3.0.4 on 2020-03-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_genevisitor_genomefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genevisitor',
            name='birthday',
        ),
    ]
