# Generated by Django 3.0.4 on 2020-03-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genetics', '0001_initial'),
        ('person', '0002_creator_genevisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSNPTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('shortDescr', models.TextField(blank=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Creator')),
                ('snp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genetics.Snp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneSnpResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True)),
                ('genotype', models.ManyToManyField(to='genetics.Genotype')),
                ('onesnptrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trait.OneSNPTrait')),
            ],
        ),
    ]
